---
- hosts: node2
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: "Copiar archivo1 al servidor"
      copy:
        src: "{{ file1 }}"
        dest: "{{ dest }}"

    - name: "Copiar archivo2 al servidor"
      copy:
        src: "{{ file2 }}"
        dest: "{{ dest }}"
        
    - name: "Iniciar y habilitar firewalld"
      shell: "systemctl start firewalld.service && systemctl enable firewalld.service"

    - name: "Agregar regla al firewall"
      shell: "firewall-cmd --add-service=postgresql --permanent"
      become: true

    - name: "Reiniciar firewall"
      shell: "systemctl restart firewalld.service"
      become: true

    - name: "Reiniciar postgresql"
      shell: "service postgresql restart"
      become: true
